name: Accessibility Scan
on:
  schedule:
    - cron: '*/60 * * * *' # Every 5 minutes
  workflow_dispatch:      # Allows manual triggers

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Run Accessibility Scan
        uses: test-party/reporter@main
        with:
          testparty_token: ${{ secrets.TESTPARTY_TOKEN }}
          repository_name: ${{ github.repository }}
          repository_id: ${{ github.repository_id }}
          urls: 'https://www.understood.org,https://www.understood.org/blog/'